### ISSUE TITLE
ClosePanel Function

### ISSUE THREAD

**Issue by emilycritter** [CodyHouse/cd-off-canvas-navigation-changelog#2]
The navigation panel does not close when a in-page link is clicked: 
e.g. when href="#0"
```
<li><a class="offnav__link" href="#0">About</a></li>
```

Can you add an event that closes the panel on click? Or make the closePanel function available?

**Comment by claudia-romano** [comment]
Hi Emily, we have updated the Off-Canvas Content component (which is a dependency of the Off-canvas Navigation) to include two custom Events you can use to toggle the panel. You can read more here:
https://codyhouse.co/ds/components/info/off-canvas-content#custom-events

You can find the updated code here:
https://codyhouse.co/ds/components/app/off-canvas-content

Cheers!
